[package]
name = "uprusty"
version = "0.1.0"
edition = "2024"
authors = ["pixam github@pixelizedambitions.com"]
license = "MIT"


[dependencies]
serde = "1.0.219"
tokio = { version = "1.46.1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"


